# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8088



# Spring配置
spring:
  profiles:
    active: druid

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.asiainfo.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

