# 项目相关配置
visual:
  # 名称
  name: Visual
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2020

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  #资源信息
  messages:
    basename: i18n/messages
  #数据源配置
  profiles:
    active: dev
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30


# 日志配置
logging:
  level:
    com.asiainfo: info
    org.springframework: info

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.asiainfo.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

#fastdep:
#  redis:
#    redis1: #连接名称
#      password: 123456
#      cluster: 58.87.77.191:7001,58.87.77.191:7002,58.87.77.191:7003,58.87.77.191:7004,58.87.77.191:7005,58.87.77.191:7006
#      lettuce: #下面为连接池的补充设置
#        shutdown-timeout: 100 # 关闭超时时间
#        pool:
#          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
#          max-idle: 8 # 连接池中的最大空闲连接
#          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#          min-idle: 0 # 连接池中的最小空闲连接
#    redis2: #连接名称
#      password: 123456
#      cluster: 58.87.77.191:6666,58.87.77.191:6667,58.87.77.191:6668,58.87.77.191:6669,58.87.77.191:6663,58.87.77.191:6662
#      lettuce: #下面为连接池的补充设置
#        shutdown-timeout: 100 # 关闭超时时间
#        pool:
#          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
#          max-idle: 8 # 连接池中的最大空闲连接
#          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#          min-idle: 0 # 连接池中的最小空闲连接
#  redis:
#    password: 123456
#    timeout: 6000ms
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
#      shutdown-timeout: 8000ms
#    cluster:
#      nodes: 58.87.77.191:7001,58.87.77.191:7002,58.87.77.191:7003,58.87.77.191:7004,58.87.77.191:7005,58.87.77.191:7006


